apiVersion: v1
kind: Service
metadata:
  name: feedback-api-service
spec:
  selector:
    app: feedback-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
