# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt
        pip install pytest flake8

    - name: Run lint
      run: flake8 .

    - name: Create dummy model for CI
      run: |
        mkdir -p models
        python scripts/create_dummy_model.py

    - name: Run tests with pytest (dummy model)
      run: USE_DUMMY_MODEL=true python -m pytest -v

    - name: Build Docker image
      run: docker build -t feedback-api -f ./docker/fastapi_app/Dockerfile .


      # Optional: push Docker image to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/feedback-api:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl for Minikube
      run: |
        minikube start --driver=docker
        kubectl config use-context minikube

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
